version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

    command: >
      sh -c "uvicorn main:app --reload --port 5000"
